### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by secretdataz** [Temtaime/aesir#1]
Aesir hash: `5ef3fae963686b2c2b14436fbe03475539b1bb70`
Compiler: DMD 2.078.0-rc.1 + Visual C++ 2017
I generated a VisualD project for Aesir with `dub gen visuald` and tweaked the solution so that it could actually find required static library files. I also changed the platform to x64.

Compile log: https://pastebin.com/nTtvStEr

**Comment by Temtaime** [comment]
Hello and happy new year :)
Try to use phobos from http://d.a-rei.ru/dmd_2017.11.22_x64.7z
Forgot to commit deprecations fix. Gimme a second

**Comment by Temtaime** [comment]
Also it seems that you forgot to add generated source files to the project ?

**Comment by secretdataz** [comment]
Ah, is this third-party DMD from a-rei.ru really a must for compiling Aesir?

**Comment by Temtaime** [comment]
Sadly yes, because an original one has some unfixed bugs.
I'll try to find a workaround to get rid of some of them.

**Comment by ViteFalcon** [comment]
I have different type of compilation issue:

```dlang
../../../.dub/packages/tt-utils-1.3.6/tt-utils/source/tt/encoding.d(88,7): Error: undefined identifier fromMBSz
../../../.dub/packages/tt-utils-1.3.6/tt-utils/source/tt/encoding.d(105,22): Error: undefined identifier toMBSz
```

[Full output](https://pastebin.com/gJ7unHSR)

I'm compiling this on Mac OSX (Sierra). BTW... is Mac supported?

**Comment by Temtaime** [comment]
Mac is not supported yet

**Comment by ViteFalcon** [comment]
Can you explain what components are platform-specific so that I can attempt to make this cross-platform?

P.S.: I'm not guaranteeing that I would get it done, but it could help others to look into it.

**Comment by Temtaime** [comment]
Just build all dependencies on mac and it should work out of the box. Also adopt package tt.
There's almost no platform-dependent code.
  I simply don't have a mac to test.

**Comment by secretdataz** [comment]
@Temtaime Is this still the case that we need a 3rd party DMD?

**Comment by Temtaime** [comment]
@secretdataz seems should be buildable with official one 2.079.
Reopen if there's some compilation errors.
