### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by felipemartins210** [Temtaime/aesir#2]
![erro client](https://user-images.githubusercontent.com/8534899/36255472-535bf68c-1236-11e8-8954-ed4e852512cf.png)

I am using rathena.

**Comment by Temtaime** [comment]
Use packetver 20170517 and disable packet obfuscation. Should work out of the box with latest rathena.

**Comment by felipemartins210** [comment]
**_I did, but now is happening it._**

![erro client](https://user-images.githubusercontent.com/8534899/36280681-3a00ea84-1282-11e8-9203-2ab6271f9159.png)

**Comment by Temtaime** [comment]
Make sure that other processes are not using grf files in time when you run the client.

**Comment by felipemartins210** [comment]
I am sure, I reboot my pc and it stills happening it.

**Comment by felipemartins210** [comment]
is it work with rathena right?

**Comment by Temtaime** [comment]
Yes, but the error is not related to the server.
Maybe you run some antivirus software ?
Try to disable it, don't know how it could interact, but anyway.

**Comment by luan122** [comment]
@felipemartins210 if you use Itau, BB, Caixa economicas as your banks, you need to uninstall their protection, since gas block alot of files that are related to RO

**Comment by felipemartins210** [comment]
nothing! i give up T_T

**Comment by edddieee** [comment]
Just for future reference.
I had the same problem when I tried to use an updated GRF, but using a kRO client from 2017 it works properly.

NOTE: The problem will happen if u tried to use an encrypted GRF.

**Comment by Temtaime** [comment]
The issue is outdated, so i think it's time to close it.
If there're new problems, feel free to create a new issue.
There'll new release in near future with many fixes.
