### ISSUE TITLE
Support for different packet versions

### ISSUE THREAD

**Issue by zhad3** [Temtaime/aesir#6]
Is there a plan to support different packet versions? I tried to test the client on the newest rAthena server (packetver 20180307) and it obviously didn't work. Trying to add support would result in the client no longer being able to work on previous versions.

I wonder if it is applicable to adapt the way rAthena handles it via conditional statements in the sending/receiving functions. The question then is where to add these conditional statements in AEsir and how to handle different data that may occur with a different version of the same packet.

Taking the signal of selecting a character and entering the world as an example: where should the condition be placed?
```d
void onCharSelected()
{
	with(ROnet)
	{
		// if PACKETVER == XXXXXXX ??
		// what about different st.ch data?
		// sendPk(CZ_ENTER2, st.ch) <-- function that handles packet version based on fixed identifier
		send!Pk0066(st.ch);
	}
}
```
Placing it there in the gui controller is not a good idea IMO and instead having a different function that handles the different packet version is more suitable. I wonder if one can assume that the data is always backwards compatible. Meaning that the newest data structure always contains the data required by the older packets. That way I think it should be relatively easy to implement.

The packets doc rAthena also states the support of different versions of the same packet which we could utilize in the packets.txt file used by AEsir:
```
Packet with combination of both different AEGIS names and different
versions with same name:

 /// Sends hotkey bar.
 /// 02b9 { <is skill>.B <id>.L <count>.W }*27 (ZC_SHORTCUT_KEY_LIST)
 /// 07d9 { <is skill>.B <id>.L <count>.W }*36 (ZC_SHORTCUT_KEY_LIST_V2, PACKETVER >= 20090603)
 /// 07d9 { <is skill>.B <id>.L <count>.W }*38 (ZC_SHORTCUT_KEY_LIST_V2, PACKETVER >= 20090617)
``` 

On a side note: I can not register on the forums because the registration window is empty.

**Comment by Temtaime** [comment]
Hello.
Thanks for the reply. 
Currently there's some refactoring and in the future all direct packet manipulations will be encapsulated in one module.
Speaking about different packet versions - i don't see any reasons why we should have it. It only adds all those spaghetti code with no gain. 
rAthena/Hercules support different packet versions - there's no problem recompile it for needed packetver for Æsir IMO.

**Comment by Temtaime** [comment]
Thanks for noting forum problems - i will dig into it.

**Comment by Temtaime** [comment]
FYI forum is fixed now
