### ISSUE TITLE
I can't grab data.7z and deps.7z files

### ISSUE THREAD

**Issue by edddieee** [Temtaime/aesir#7]
Hello @Temtaime !

Few weeks ago I was taking a look in this project and now I would like to make some contribution, but unfortunately I can't download the `data.7z` and `deps.7z` files anymore.

Just let me know if u are still working in this project or if you have intention to keep working on it, perhaps I could make some contribution!

Thank you

**Comment by Temtaime** [comment]
Hello.
Thanks for being interested in the project. 
Yes, I'm working on it and will release major commit with new ui in the near future. 
You cannot download the files because I'm upgrading the hardware on hosting server. 
It will be up in 2-3 days.

**Comment by edddieee** [comment]
Thanks for the information! I'm excited to see this new release!
