### ISSUE TITLE
Project Still Alive?

### ISSUE THREAD

**Issue by Inzanity99** [Temtaime/aesir#8]
Tried to reach you everywhere else without an answer.
Trying here now.
I havent seen any update on this project in quite some time + no forum activity + no patreon activity.

I am very much interested in this projects progress and would like to see it completed!
(I am able to support you financially and otherwise)
Please let me know if you intend to finish this project!
Inzanity#1558 (discord)

**Comment by Temtaime** [comment]
Hello. Thanks for your interest in this project!
Yes, i didn't login to discord recently. Just send your a friend request. Sorry that i missed you message on the forum(i'm getting tons of emails from bots, and currently didn't deal with it). If you have Telegram, you can always contact me using it @temtaime 
Project is still alive, i'm currently finishing new ui, i hoped release it early this year, but didn't have enough time.
Any help is always greatly appreciated.
Kind regards.

**Comment by Neo-Mind** [comment]
FYI. The website is also not working... so more people are bound to think the project is discontinued.

**Comment by Temtaime** [comment]
Hello.
The site works normally. At first, there was a wrong redirect, but now it's fixed.
Site was moved to https://aesir.perfontain.cc/forum/ JFYI.
Sorry for so little info, just having too much work :( Going to fix it, but don't know how for the moment
