### ISSUE TITLE
Missing nuklear_x64.lib 

### ISSUE THREAD

**Issue by RolandKaechele** [Temtaime/aesir#9]
Hi,

I have tried to compile and got an error regarding missing nuklear_x64.lib

Maybe it‘s missing in deps.7z, can you please add the file or link?

BR
Roland

**Comment by Temtaime** [comment]
Hello.
Current master is in Work In Progress state, so i wouldn't expect too much from it. But i have added the file to deps.7z. Redownload.

Kind regards
